jobs:
  call-zapier-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Call Zapier Webhook
        uses: gpuliyar/zapier-webhook-action@v1.0.0
        with:
          # Zapier Webhook ID https://hooks.zapier.com/hooks/catch/{webhook-id} (Mandatory)
          webhook-id: https://hooks.zapier.com/hooks/catch/15069498/3udysaz/

          # Webhook call Http method (Optional)
          # Allowed http method verbs - GET, POST, PUT
          # default - GET
          method: POST
 
          # If the developer prefers getting an empty response (Optional)
          # default - false (not silent)
          silent: false

          # Payload to send to the Zapier webhook (Optional)
          message: this action is awesome
